name = input("Hello , what your name")
age = int(input("How old are you"))
print("Nice to meet you %s \n" % name)
print("you are %d yare old \n" % age)
print("Bye %s \n" % name)
ch = int(input("Pres any key to continue.."))
